---
abstract: 'Catalyst based application'
author:
  - 'Kieren Diment'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBAuthTest
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: '5.80002'
  Config::General: 0
  DBICx::TestDatabase: 0
  DBIx::Class::TimeStamp: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
